travis:
  secure:
    BINSTAR_TOKEN: t83Ne8eVAjfLc8NX4RXkiQnw04dFmSWldwShYU4MkpN+aakYuQGEh9kUDrN8m/POA0IjevywuK0dGWyHBvSXvgh0ojTe23JSV8u1GWc5zETAx64dIA5sPHSVp0c36TyO9NV2JjoohmMUukq/y3jgiXFIA1+9L/lAgo9fcgU7QMhB7rIEYnINbvWPYcI/rq5RSaEMXqFkzUTn++nJ3Kcel5DuSXhU9EHYpZpfUllKaZh+G7huyJwL1HTTc58xbQ9ncSNFgk8nFnxG/HXqn9nS8Wj16afjpNu2/HdOgou/uDqMEVkgsLoIEUfct82jsuQXVlMlXTJE8a40pR1kawhZMHF0KZMjTsS4J1/ZxG+2/g3w9MZ+D3bQVso7zRIVEq7PaRsxjpmRNHm2bRzIyst0T5HhQ2sTuI6HuB3r/5IvMlj2lTW8JdmgkmG/kpq4UJX1ZA2l78JxO2JzK2AnfjqJDbXlw5VXPQpDxxJjq07ZGyXJh8JTJA1ckatk/1Lj9WPEikgAOCeQs/Z9kBMzp/scqG3kAHivAfNn6NNJDmiN2516s9hx03dY+X7mGROhxzEbvkFBcx8d76LYG0bwT7A/tEkJp7HWIddnywo4tNzSSyhNEKznYdwXgDT5gmJu7Hv115ysLSA/JaoS40qGeyL9ZxDO9OVCDJB9XMrkMZbwvNc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
